### ISSUE TITLE
Similar Vim built-in feature

### ISSUE THREAD

**Issue by odnoletkov** [obcat/vim-hitspop#7]
Standard Vim supports this with `set shortmess-=S`

> 	  S     do not show search count message when searching, e.g.
>	        "[1/5]"

It works a little different:

* Displays the count at the bottom right
* Doesn't count more than 99 total occurances

Are there any other differences and benefits of using this plugin?

**Comment by obcat** [comment]
Good question :smile_cat:

The message shown by `shortmess-=S` will disappear after redrawing.
This means lovers of

```vim
nnoremap n nzz
```

can never see the message.

Also, vim-hitspop updates the search information on every `CursorMoved`,
but `shortmess-=S` doesn't, so it shows inaccurate information sometimes.

**Comment by odnoletkov** [comment]
Fair enough, maybe worth mentioning these in the README
